WIDTH = 1280
HEIGHT = 720
FPS = 30

WAVE_WIDTH = 600
WAVE_HEIGHT = 50
WAVE_CENTER_Y = HEIGHT // 2
WAVE_X_START = (WIDTH - WAVE_WIDTH) // 2

SEEK_BAR_H = 2
SEEK_BAR_Y = HEIGHT - 40
SEEK_BAR_X = (WIDTH - WAVE_WIDTH) // 2
SEEK_BAR_W = WAVE_WIDTH

TEXT_X = SEEK_BAR_X
TIME_MARGIN = 7
TEXT_Y_TIME = SEEK_BAR_Y - 13 - TIME_MARGIN
TEXT_Y_ALBUM = TEXT_Y_TIME - 22
TEXT_Y_ARTIST = TEXT_Y_ALBUM - 22
TEXT_Y_TITLE = TEXT_Y_ARTIST - 32

SMOOTHING_WINDOW = 15
TEMPORAL_ALPHA = 0.35

WAVE_FADE_WIDTH = 60

LANG_PREFIXES: dict[str, dict[str, str]] = {
    "en": {"artist": "by ", "album": "from "},
    "pt": {"artist": "por ", "album": "de "},
}

FADE_DURATION = 3.0
FADE_DELAY_WAVE = 0.5
FADE_DELAY_UI = 1.0
